import 'dart:async';

import 'package:flutter/material.dart';

/// This class is generated by the flappy_translator package
/// Please do not change anything manually in this file, instead re-generate it when changes are available
class I18n {
  String get appTitle => _getText("appTitle");

  String get greeting => _getText("greeting");

  String get subtitle => _getText("subtitle");

  String description({
    required String var1,
  }) {
    String text = _getText("description");
    text = text.replaceAll("%1\$s", var1);
    return text;
  }

  String littleTest({
    required int age,
  }) {
    String text = _getText("littleTest");
    if (age != null) {
      text = text.replaceAll("%age\$d", age.toString());
    }
    return text;
  }

  static Map<String, String>? _localizedValues = <String,String>{};

  static final Map<String, String> _enValues = {
    "appTitle": "Luvu Gift App",
    "greeting": "Hello",
    "subtitle": "A subtitle",
    "description": "Text with a variable: %1\$s",
    "littleTest":
    "Here is, for the example, \"a test\" with the variable %age\$d",
  };

  static final Map<String, String> _deValues = {
    "appTitle": "Luvu Geschenke App",
    "greeting": "Hallo",
    "subtitle": "Ein Untertitle",
    "description": "Text mit einer Variable: %1\$s",
    "littleTest":
    "Hier ist, zum Beispiel, \"ein Test\" mit der Variable %age\$d",
  };

  static final Map<String, Map<String, String>> _allValues = {
    "en": _enValues,
    "de": _deValues,
  };

  I18n(Locale locale) {
    _locale = locale;
    _localizedValues = null;
  }

  Locale? _locale;

  static I18n? of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }

  String _getText(String key) {
    return _localizedValues![key] ?? '** $key not found';
  }

  Locale? get currentLocale => _locale;

  String get currentLanguage => _locale!.languageCode;

  static Future<I18n> load(Locale locale) async {
    final translations = I18n(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('de'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}